chore: updates

diff --git a/ExquisiteInstaller b/ExquisiteInstaller
--- a/ExquisiteInstaller
+++ b/ExquisiteInstaller
@@ -24,8 +24,8 @@ date=$(date +%Y%m%d-%H%M%S)
 
 logo() {
 
-	local text="${1:?}"
-	echo -en "                                  
+    local text="${1:?}"
+    echo -en "                                  
   
 ███████╗██╗░░██╗░██████╗░██╗░░░██╗██╗░██████╗██╗████████╗███████╗
 ██╔════╝╚██╗██╔╝██╔═══██╗██║░░░██║██║██╔════╝██║╚══██╔══╝██╔════╝
@@ -42,14 +42,14 @@ logo() {
 ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░╚═════╝░
 
 The Most Exquisite Dotfiles in the Universe\n\n"
-	printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
+    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
 }
 
 ########## ---------- You must not run this as root ---------- ##########
 
 if [ "$(id -u)" = 0 ]; then
-	echo "This script MUST NOT be run as root user."
-	exit 1
+    echo "This script MUST NOT be run as root user."
+    exit 1
 fi
 
 ########## ---------- Welcome ---------- ##########
@@ -58,12 +58,12 @@ logo "Welcome!"
 printf '%s%sThis script will check if you have the necessary dependencies, and if not, it will install them. Then, it will clone the RICE in your HOME directory.\nAfter that, it will create a secure backup of your files, and then copy the new files to your computer.\n\nMy dotfiles DO NOT modify any of your system configurations.\nYou will be prompted for your root password to install missing dependencies and/or to switch to zsh shell if its not your default.\n\nThis script doesnt have the potential power to break your system, it only copies files from my repository to your HOME directory.%s\n\n' "${BLD}" "${CRE}" "${CNC}"
 
 while true; do
-	read -rp " Do you wish to continue? [y/N]: " yn
-	case $yn in
-	[Yy]*) break ;;
-	[Nn]*) exit ;;
-	*) printf " Error: only write 'y' or 'n'\n\n" ;;
-	esac
+    read -rp " Do you wish to continue? [y/N]: " yn
+    case $yn in
+    [Yy]*) break ;;
+    [Nn]*) exit ;;
+    *) printf " Error: only write 'y' or 'n'\n\n" ;;
+    esac
 done
 clear
 
@@ -72,28 +72,28 @@ clear
 logo "Initializing perfection..."
 
 dependencies=(base-devel rustup pacman-contrib bspwm polybar sxhkd
-	alacritty brightnessctl dunst rofi lsd stalonetray auto-cpufreq
-	jq polkit-gnome git playerctl mpd xclip copyq redshift
-	ncmpcpp geany ranger mpc picom xdo xdotool jgmenu shotwell
-	feh ueberzug maim pamixer libwebp xdg-user-dirs
-	webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme
-	ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels
-	zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting xorg-xsetroot xorg-xwininfo xorg-xrandr)
+    alacritty brightnessctl dunst rofi lsd stalonetray auto-cpufreq
+    jq polkit-gnome git playerctl mpd xclip copyq redshift
+    ncmpcpp geany ranger mpc picom xdo xdotool jgmenu shotwell
+    feh ueberzug maim pamixer libwebp xdg-user-dirs
+    webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme
+    ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels
+    zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting xorg-xsetroot xorg-xwininfo xorg-xrandr)
 
 is_installed() {
-	pacman -Qi "$1" &>/dev/null
-	return $?
+    pacman -Qi "$1" &>/dev/null
+    return $?
 }
 
 printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
 for packages in "${dependencies[@]}"; do
-	if ! is_installed "$packages"; then
-		sudo pacman -S "$packages" --noconfirm
-		printf "\n"
-	else
-		printf '%s%s is already installed on your system!%s\n' "${CGR}" "$packages" "${CNC}"
-		sleep 1
-	fi
+    if ! is_installed "$packages"; then
+        sudo pacman -S "$packages" --noconfirm
+        printf "\n"
+    else
+        printf '%s%s is already installed on your system!%s\n' "${CGR}" "$packages" "${CNC}"
+        sleep 1
+    fi
 done
 sleep 3
 clear
@@ -102,10 +102,10 @@ clear
 
 logo "Preparing Folders..."
 if [ ! -e $HOME/.config/user-dirs.dirs ]; then
-	xdg-user-dirs-update
-	echo "Creating xdg-user-dirs"
+    xdg-user-dirs-update
+    echo "Creating xdg-user-dirs"
 else
-	echo "user-dirs.dirs already exists"
+    echo "user-dirs.dirs already exists"
 fi
 sleep 2
 clear
@@ -124,8 +124,8 @@ repo_dir="$HOME/dotfiles"
 # git clone --depth=1 https://github.com/ejsadiarin/dotfiles.git
 
 if [ -d "$repo_dir" ]; then
-	printf "Removing existing dotfiles repository\n"
-	rm -rf "$repo_dir"
+    printf "Removing existing dotfiles repository\n"
+    rm -rf "$repo_dir"
 fi
 
 printf "Cloning dotfiles from %s\n" "$repo_url"
@@ -141,34 +141,34 @@ printf "Backup files will be stored in %s%s%s/.RiceBackup%s \n\n" "${BLD}" "${CR
 sleep 10
 
 if [ ! -d "$backup_folder" ]; then
-	mkdir -p "$backup_folder"
+    mkdir -p "$backup_folder"
 fi
 
 for folder in bspwm alacritty picom rofi eww sxhkd dunst polybar ncmpcpp nvim ranger zsh mpd paru; do
-	if [ -d "$HOME/.config/$folder" ]; then
-		mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date"
-		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-	else
-		echo "The folder $folder does not exist in $HOME/.config/"
-	fi
+    if [ -d "$HOME/.config/$folder" ]; then
+        mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date"
+        echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
+    else
+        echo "The folder $folder does not exist in $HOME/.config/"
+    fi
 done
 
 for folder in chrome; do
-	if [ -d "$HOME"/.mozilla/firefox/*.default-release/$folder ]; then
-		mv "$HOME"/.mozilla/firefox/*.default-release/$folder "$backup_folder"/${folder}_$date
-		echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
-	else
-		echo "The folder $folder does not exist in $HOME/.mozilla/firefox/"
-	fi
+    if [ -d "$HOME"/.mozilla/firefox/*.default-release/$folder ]; then
+        mv "$HOME"/.mozilla/firefox/*.default-release/$folder "$backup_folder"/${folder}_$date
+        echo "$folder folder backed up successfully at $backup_folder/${folder}_$date"
+    else
+        echo "The folder $folder does not exist in $HOME/.mozilla/firefox/"
+    fi
 done
 
 for file in user.js; do
-	if [ -e "$HOME"/.mozilla/firefox/*.default-release/$file ]; then
-		mv "$HOME"/.mozilla/firefox/*.default-release/$file "$backup_folder"/${file}_$date
-		echo "$file file backed up successfully at $backup_folder/${file}_$date"
-	else
-		echo "The file $file does not exist in $HOME/.mozilla/firefox/"
-	fi
+    if [ -e "$HOME"/.mozilla/firefox/*.default-release/$file ]; then
+        mv "$HOME"/.mozilla/firefox/*.default-release/$file "$backup_folder"/${file}_$date
+        echo "$file file backed up successfully at $backup_folder/${file}_$date"
+    else
+        echo "The file $file does not exist in $HOME/.mozilla/firefox/"
+    fi
 done
 
 [ -f ~/.zshrc ] && mv ~/.zshrc ~/.RiceBackup/.zshrc-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
@@ -187,58 +187,58 @@ echo "Copying files to respective directories..."
 [ ! -d ~/.local/share/fonts ] && mkdir -p ~/.local/share/fonts
 
 for archivos in ~/dotfiles/config/*; do
-	cp -R "${archivos}" ~/.config/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-		sleep 1
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+    cp -R "${archivos}" ~/.config/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+        sleep 1
+    else
+        printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+        sleep 1
+    fi
 done
 
 for archivos in ~/dotfiles/misc/bin/*; do
-	cp -R "${archivos}" ~/.local/bin/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-		sleep 1
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+    cp -R "${archivos}" ~/.local/bin/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+        sleep 1
+    else
+        printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+        sleep 1
+    fi
 done
 
 for archivos in ~/dotfiles/misc/applications/*; do
-	cp -R "${archivos}" ~/.local/share/applications/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-		sleep 1
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+    cp -R "${archivos}" ~/.local/share/applications/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s file copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+        sleep 1
+    else
+        printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+        sleep 1
+    fi
 done
 
 for archivos in ~/dotfiles/misc/fonts/*; do
-	cp -R "${archivos}" ~/.local/share/fonts/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-		sleep 1
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+    cp -R "${archivos}" ~/.local/share/fonts/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+        sleep 1
+    else
+        printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+        sleep 1
+    fi
 done
 
 for archivos in ~/dotfiles/misc/firefox/*; do
-	cp -R "${archivos}" ~/.mozilla/firefox/*.default-release/
-	if [ $? -eq 0 ]; then
-		printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
-		sleep 1
-	else
-		printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
-		sleep 1
-	fi
+    cp -R "${archivos}" ~/.mozilla/firefox/*.default-release/
+    if [ $? -eq 0 ]; then
+        printf "%s%s%s folder copied succesfully!%s\n" "${BLD}" "${CGR}" "${archivos}" "${CNC}"
+        sleep 1
+    else
+        printf "%s%s%s failed to been copied, you must copy it manually%s\n" "${BLD}" "${CRE}" "${archivos}" "${CNC}"
+        sleep 1
+    fi
 done
 
 cp -f "$HOME"/dotfiles/home/.zshrc "$HOME"
@@ -252,54 +252,54 @@ logo "installing Paru, Eww, tdrop & xqp"
 
 # Installing Paru
 if command -v paru >/dev/null 2>&1; then
-	printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "%s%sParu is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
-	printf "%s%sInstalling paru%s\n" "${BLD}" "${CBL}" "${CNC}"
-	{
-		cd "$HOME" || exit
-		git clone https://aur.archlinux.org/paru-bin.git
-		cd paru-bin || exit
-		makepkg -si --noconfirm
-	} || {
-		printf "\n%s%sFailed to install Paru. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
-	}
+    printf "%s%sInstalling paru%s\n" "${BLD}" "${CBL}" "${CNC}"
+    {
+        cd "$HOME" || exit
+        git clone https://aur.archlinux.org/paru-bin.git
+        cd paru-bin || exit
+        makepkg -si --noconfirm
+    } || {
+        printf "\n%s%sFailed to install Paru. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+    }
 fi
 
 # Intalling tdrop for scratchpads
 if command -v tdrop >/dev/null 2>&1; then
-	printf "\n%s%sTdrop is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "\n%s%sTdrop is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
-	printf "\n%s%sInstalling tdrop, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
-	paru -S tdrop-git --skipreview --noconfirm
-	paru -S system-monitoring-center --skipreview --noconfirm
+    printf "\n%s%sInstalling tdrop, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
+    paru -S tdrop-git --skipreview --noconfirm
+    paru -S system-monitoring-center --skipreview --noconfirm
 fi
 
 # Intalling xqpp
 if command -v xqp >/dev/null 2>&1; then
-	printf "\n%s%sxqp is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "\n%s%sxqp is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
-	printf "\n%s%sInstalling xqp, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
-	paru -S xqp --skipreview --noconfirm
+    printf "\n%s%sInstalling xqp, this should be fast!%s\n" "${BLD}" "${CBL}" "${CNC}"
+    paru -S xqp --skipreview --noconfirm
 fi
 
 # Installing Eww
 if command -v eww >/dev/null 2>&1; then
-	printf "\n%s%sEww is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "\n%s%sEww is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
 else
-	printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
-	{
-		sudo pacman -S rustup --noconfirm
-		cd "$HOME" || exit
-		git clone https://github.com/elkowar/eww
-		cd eww || exit
-		cargo build --release --no-default-features --features x11
-		sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
-	} && {
-		cd "$HOME" || exit
-		rm -rf {paru-bin,.cargo,.rustup,eww}
-	} || {
-		printf "\n%s%sFailed to install Eww. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
-	}
+    printf "\n%s%sInstalling Eww, this could take 10 mins or more.%s\n" "${BLD}" "${CBL}" "${CNC}"
+    {
+        sudo pacman -S rustup --noconfirm
+        cd "$HOME" || exit
+        git clone https://github.com/elkowar/eww
+        cd eww || exit
+        cargo build --release --no-default-features --features x11
+        sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
+    } && {
+        cd "$HOME" || exit
+        rm -rf {paru-bin,.cargo,.rustup,eww}
+    } || {
+        printf "\n%s%sFailed to install Eww. You may need to install it manually%s\n" "${BLD}" "${CRE}" "${CNC}"
+    }
 fi
 
 ########## ---------- Enabling MPD service ---------- ##########
@@ -307,9 +307,9 @@ fi
 logo "Enabling mpd service..."
 
 if systemctl is-enabled --quiet mpd.service; then
-	printf "\n%s%sDisabling and stopping the global mpd service%s\n" "${BLD}" "${CBL}" "${CNC}"
-	sudo systemctl stop mpd.service
-	sudo systemctl disable mpd.service
+    printf "\n%s%sDisabling and stopping the global mpd service%s\n" "${BLD}" "${CBL}" "${CNC}"
+    sudo systemctl stop mpd.service
+    sudo systemctl disable mpd.service
 fi
 
 printf "\n%s%sEnabling and starting the user-level mpd service%s\n" "${BLD}" "${CYE}" "${CNC}"
@@ -323,12 +323,12 @@ sleep 2
 logo "Changing default shell to zsh..."
 
 if [[ $SHELL != "/usr/bin/zsh" ]]; then
-	printf "\n%s%sChanging your shell to zsh. Your root password is needed.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
-	# Cambia la shell a zsh
-	chsh -s /usr/bin/zsh
-	printf "%s%sShell changed to zsh. Please reboot.%s\n\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "\n%s%sChanging your shell to zsh. Your root password is needed.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
+    # Cambia la shell a zsh
+    chsh -s /usr/bin/zsh
+    printf "%s%sShell changed to zsh. Please reboot.%s\n\n" "${BLD}" "${CGR}" "${CNC}"
 else
-	printf "%s%sYour shell is already zsh\nGood bye! installation finished, now reboot%s\n" "${BLD}" "${CGR}" "${CNC}"
+    printf "%s%sYour shell is already zsh\nGood bye! installation finished, now reboot%s\n" "${BLD}" "${CGR}" "${CNC}"
 fi
 zsh
 
