feat: improve ansible playbooks, roles, and init script

diff --git a/ansible/init_control_node b/ansible/init_control_node
--- a/ansible/init_control_node
+++ b/ansible/init_control_node
@@ -53,7 +53,7 @@ RIGHT_ANGLE="${GREEN}\xE2\x88\x9F${NC}" # ∟
 #################
 
 DOTFILES="$HOME/dotfiles"
-CHECK_IF_FIRST_RUN="$HOME/dotfiles/.exquisite_release"
+RELEASE_FILE="$HOME/dotfiles/.exquisite_release"
 EXQUILOG="$HOME/dotfiles/.exquisite_log"
 VAULT_PASSWORD_FILE="$HOME/dotfiles/decrypted_mp"
 date_today=$(date +"%Y-%m-%d %H:%M:%S")
@@ -121,102 +121,101 @@ stdout_msg() {
 arch_setup() {
     stdout_msg "START" "arch-setup" "Running arch setup"
     write_to_exquilog "INFO" "arch-setup" "Initiate arch setup"
-    # install paru
-    if command -v paru >/dev/null 2>&1; then
-        stdout_msg "INFO" "paru" "Paru is already installed."
-        write_to_exquilog "INFO" "paru" "Paru is already installed."
-    else
-        stdout_msg "INSTALLING" "paru" "Installing paru..."
-        write_to_exquilog "INFO" "paru" "Installing paru..."
-        {
-            cd "$HOME" || exit
-            git clone https://aur.archlinux.org/paru-bin.git
-            cd paru-bin || exit
-            makepkg -si --noconfirm
-            stdout_msg "INSTALLED" "paru" "Paru is now installed!"
-            write_to_exquilog "INFO" "paru" "Paru is now installed!"
-        } || {
-            stdout_msg "ERROR" "paru" "Failed to install paru. Skipping..."
-            write_to_exquilog "ERROR" "paru" "Failed to install paru. Need to install manually."
-        }
-    fi
 
-    # install ansible
-    if command -v ansible >/dev/null 2>&1; then
-        stdout_msg "INFO" "ansible" "Ansible is already installed."
-        write_to_exquilog "INFO" "ansible" "Ansible is already installed."
-    else
-        stdout_msg "INSTALLING" "ansible" "Installing ansible..."
-        write_to_exquilog "INFO" "ansible" "Installing ansible..."
-        {
-            sudo pacman -S ansible
-            stdout_msg "INSTALLED" "ansible" "Ansible is now installed!"
-            write_to_exquilog "INFO" "ansible" "Ansible is now installed!"
-        } || {
-            stdout_msg "ERROR" "ansible" "Failed to install ansible. Skipping..."
-            write_to_exquilog "ERROR" "ansible" "Failed to install ansible. Need to install manually."
-        }
-    fi
-
-    # install python, pip deps
-    if pacman -Q python >/dev/null 2>&1; then
-        local version=""
-        version=$(python3 --version) || {
-            version=$(python --version) || version=$(python2 --version) # fallback
-        }
-        stdout_msg "INFO" "python" "Python (ver: ${version}) is already installed."
-        write_to_exquilog "INFO" "python" "Python (ver: ${version}) is already installed."
-    else
-        stdout_msg "INSTALLING" "python" "Installing python..."
-        write_to_exquilog "INFO" "python" "Installing python..."
-        {
-            sudo pacman -S python
-            stdout_msg "INSTALLED" "python" "Python is now installed!"
-            write_to_exquilog "INFO" "python" "Python is now installed!"
-        } || {
-            stdout_msg "ERROR" "python" "Failed to install python. Skipping..."
-            write_to_exquilog "ERROR" "python" "Failed to install python."
-        }
-        stdout_msg "INSTALLING" "python" "Installing python-pip..."
-        write_to_exquilog "INFO" "python-pip" "Installing python-pip..."
-        {
-            sudo pacman -S python-pip
-            stdout_msg "INSTALLED" "python-pip" "Python-pip is now installed!"
-            write_to_exquilog "INFO" "python-pip" "Python-pip is now installed!"
-        } || {
-            stdout_msg "ERROR" "python-pip" "Failed to install python-pip. Skipping..."
-            write_to_exquilog "ERROR" "python-pip" "Failed to install python-pip."
-        }
-    fi
-
-    # install openssh (most likely installed already but why not ensure it)
-    if pacman -Q openssh >/dev/null 2>&1; then
-        stdout_msg "INFO" "openssh" "OpenSSH is already installed."
-        write_to_exquilog "INFO" "openssh" "OpenSSH is already installed."
-    else
-        stdout_msg "INSTALLING" "openssh" "Installing openssh..."
-        write_to_exquilog "INFO" "openssh" "Installing openssh..."
-        {
-            sudo pacman -S openssh
-            stdout_msg "INSTALLED" "openssh" "OpenSSH is now installed!"
-            write_to_exquilog "INFO" "openssh" "OpenSSH is now installed!"
-        } || {
-            stdout_msg "ERROR" "openssh" "Failed to install openssh. Skipping..."
-            write_to_exquilog "ERROR" "openssh" "Failed to install openssh."
-        }
-    fi
-
-    # do not automate enabling sshd to avoid unwanted opened services since it is optional
-    stdout_msg "WARNING" "openssh-server" "Manually start/enable sshd via systemctl to make host a ssh server (Optional)."
-
-    # install necessary ansible-galaxy collections
-    if [[ ! -f $CHECK_IF_FIRST_RUN ]]; then
+    if [[ ! -f $RELEASE_FILE ]]; then
         stdout_msg "DETECTED" "first run" "Detected dotfiles setup first run..."
         write_to_exquilog "INFO" "FIRST RUN" "Detected dotfiles setup first run..."
 
+        # --- Install operations for first run ----
+
+        # install paru
+        if command -v paru >/dev/null 2>&1; then
+            stdout_msg "INFO" "paru" "Paru is already installed."
+            write_to_exquilog "INFO" "paru" "Paru is already installed."
+        else
+            stdout_msg "INSTALLING" "paru" "Installing paru..."
+            write_to_exquilog "INFO" "paru" "Installing paru..."
+            {
+                cd "$HOME" || exit
+                git clone https://aur.archlinux.org/paru-bin.git
+                cd paru-bin || exit
+                makepkg -si --noconfirm
+                stdout_msg "INSTALLED" "paru" "Paru is now installed!"
+                write_to_exquilog "INFO" "paru" "Paru is now installed!"
+            } || {
+                stdout_msg "ERROR" "paru" "Failed to install paru. Skipping..."
+                write_to_exquilog "ERROR" "paru" "Failed to install paru. Need to install manually."
+            }
+        fi
+
+        # install ansible
+        if command -v ansible >/dev/null 2>&1; then
+            stdout_msg "INFO" "ansible" "Ansible is already installed."
+            write_to_exquilog "INFO" "ansible" "Ansible is already installed."
+        else
+            stdout_msg "INSTALLING" "ansible" "Installing ansible..."
+            write_to_exquilog "INFO" "ansible" "Installing ansible..."
+            {
+                sudo pacman -S ansible
+                stdout_msg "INSTALLED" "ansible" "Ansible is now installed!"
+                write_to_exquilog "INFO" "ansible" "Ansible is now installed!"
+            } || {
+                stdout_msg "ERROR" "ansible" "Failed to install ansible. Skipping..."
+                write_to_exquilog "ERROR" "ansible" "Failed to install ansible. Need to install manually."
+            }
+        fi
+
+        # install python, pip deps
+        if pacman -Q python >/dev/null 2>&1; then
+            local version=""
+            version=$(python3 --version) || {
+                version=$(python --version) || version=$(python2 --version) # fallback
+            }
+            stdout_msg "INFO" "python" "Python (ver: ${version}) is already installed."
+            write_to_exquilog "INFO" "python" "Python (ver: ${version}) is already installed."
+        else
+            stdout_msg "INSTALLING" "python" "Installing python..."
+            write_to_exquilog "INFO" "python" "Installing python..."
+            {
+                sudo pacman -S python
+                stdout_msg "INSTALLED" "python" "Python is now installed!"
+                write_to_exquilog "INFO" "python" "Python is now installed!"
+            } || {
+                stdout_msg "ERROR" "python" "Failed to install python. Skipping..."
+                write_to_exquilog "ERROR" "python" "Failed to install python."
+            }
+            stdout_msg "INSTALLING" "python" "Installing python-pip..."
+            write_to_exquilog "INFO" "python-pip" "Installing python-pip..."
+            {
+                sudo pacman -S python-pip
+                stdout_msg "INSTALLED" "python-pip" "Python-pip is now installed!"
+                write_to_exquilog "INFO" "python-pip" "Python-pip is now installed!"
+            } || {
+                stdout_msg "ERROR" "python-pip" "Failed to install python-pip. Skipping..."
+                write_to_exquilog "ERROR" "python-pip" "Failed to install python-pip."
+            }
+        fi
+
+        # install openssh (most likely installed already but why not ensure it)
+        if pacman -Q openssh >/dev/null 2>&1; then
+            stdout_msg "INFO" "openssh" "OpenSSH is already installed."
+            write_to_exquilog "INFO" "openssh" "OpenSSH is already installed."
+        else
+            stdout_msg "INSTALLING" "openssh" "Installing openssh..."
+            write_to_exquilog "INFO" "openssh" "Installing openssh..."
+            {
+                sudo pacman -S openssh
+                stdout_msg "INSTALLED" "openssh" "OpenSSH is now installed!"
+                write_to_exquilog "INFO" "openssh" "OpenSSH is now installed!"
+            } || {
+                stdout_msg "ERROR" "openssh" "Failed to install openssh. Skipping..."
+                write_to_exquilog "ERROR" "openssh" "Failed to install openssh."
+            }
+        fi
+
+        # install necessary ansible-galaxy collections
         stdout_msg "INSTALLING" "ansible-galaxy" "Installing necessary collections..."
         write_to_exquilog "INFO" "ansible-galaxy" "Installing necessary collections"
-
         {
             ansible-galaxy collection install -r "$DOTFILES"/ansible/collection/requirements.yml >/dev/null 2>&1
             ansible-galaxy collection install -r "$DOTFILES"/ansible/collection/arch.yml >/dev/null 2>&1
@@ -227,10 +226,17 @@ arch_setup() {
             write_to_exquilog "ERROR" "ansible-galaxy" "Failed to install openssh."
         }
 
+        # do not automate enabling sshd to avoid unwanted opened services since it is optional
+        stdout_msg "WARNING" "openssh-server" "Manually start/enable sshd via systemctl to make host a ssh server (Optional)."
+
+        stdout_msg "INFO" "arch-setup" "Setup done! [$date_today]"
+        write_to_exquilog "INFO" "ansible-galaxy" "Setup done!"
     else
+        # --- Update operations for subsequent runs ----
+
+        # update ansible-galaxy collections
         stdout_msg "UPDATING" "ansible-galaxy" "Updating necessary collections"
         write_to_exquilog "INFO" "ansible-galaxy" "Updating necessary collections"
-
         {
             ansible-galaxy collection install -r "$DOTFILES"/ansible/collection/requirements.yml >/dev/null 2>&1
             ansible-galaxy collection install -r "$DOTFILES"/ansible/collection/arch.yml >/dev/null 2>&1
@@ -240,10 +246,9 @@ arch_setup() {
             stdout_msg "ERROR" "ansible-galaxy" "Failed to update collections. Update manually."
             write_to_exquilog "ERROR" "ansible-galaxy" "Failed to update openssh."
         }
+        stdout_msg "INFO" "arch-setup" "Update done! [$date_today]"
+        write_to_exquilog "INFO" "ansible-galaxy" "Update done!"
     fi
-
-    stdout_msg "DONE" "arch-setup" "Setup done! [$date_today]"
-    write_to_exquilog "INFO" "ansible-galaxy" "Setup done!"
 }
 
 debian_setup() {
@@ -320,7 +325,7 @@ debian_setup() {
     stdout_msg "WARNING" "openssh-server" "Manually start/enable sshd via systemctl to make host a ssh server (Optional)."
 
     # install necessary ansible-galaxy collections
-    if [[ ! -f $CHECK_IF_FIRST_RUN ]]; then
+    if [[ ! -f $RELEASE_FILE ]]; then
         stdout_msg "DETECTED" "first run" "Detected dotfiles setup first run..."
         write_to_exquilog "INFO" "FIRST RUN" "Detected dotfiles setup first run..."
 
@@ -341,7 +346,7 @@ debian_setup() {
         write_to_exquilog "INFO" "ansible-galaxy" "Collections successfully updated!"
     fi
 
-    stdout_msg "DONE" "debian-setup" "Setup done! [$date_today]"
+    stdout_msg "INFO" "debian-setup" "Setup done! [$date_today]"
     write_to_exquilog "INFO" "ansible-galaxy" "Setup done!"
 }
 
@@ -365,18 +370,18 @@ main() {
     # Detect OS/Distro and execute setups
     if [[ "$OS" == "arch" ]]; then # check_if_arch='cat /etc/os-release | grep -i "arch"'
         arch_setup
-        if [[ ! -f "$CHECK_IF_FIRST_RUN" ]]; then
-            touch "$CHECK_IF_FIRST_RUN"
+        if [[ ! -f "$RELEASE_FILE" ]]; then
+            touch "$RELEASE_FILE"
         fi
     elif [[ "$OS" == "debian" ]]; then
         debian_setup
-        if [[ ! -f "$CHECK_IF_FIRST_RUN" ]]; then
-            touch "$CHECK_IF_FIRST_RUN"
+        if [[ ! -f "$RELEASE_FILE" ]]; then
+            touch "$RELEASE_FILE"
         fi
         # elif [[ "$OS" == "fedora" ]]; then
         #   arch_setup
-        #   if [[ ! -f "$CHECK_IF_FIRST_RUN" ]]; then
-        #     touch "$CHECK_IF_FIRST_RUN"
+        #   if [[ ! -f "$RELEASE_FILE" ]]; then
+        #     touch "$RELEASE_FILE"
         #   fi
     else
         # echo 'Skipping: Not an Arch-based system... btw'
